=== blaec/masterjava_3_200617/src/main/resources/payload.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://javaops.ru"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://javaops.ru"
           elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:element name="Payload">
        <xs:complexType>
            <xs:all>
                <xs:element name="Cities">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="unbounded">
                            <xs:element ref="City"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Projects">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="unbounded">
                            <xs:element ref="Project"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Groups">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="unbounded">
                            <xs:element ref="Group"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Users">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="User"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="User">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="fullName"/>
            </xs:sequence>
            <xs:attribute type="emailAddress" name="email" use="required"/>
            <xs:attribute type="xs:IDREF" name="city" use="required"/>
            <xs:attribute type="flagType" name="flag" use="required"/>
            <xs:attribute type="xs:IDREFS" name="group"/>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="eyecolor">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="blue|brown|green|grey"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="Group">
        <xs:complexType>
            <xs:attribute type="groupType" name="type" use="required"/>
            <xs:attribute type="xs:ID" name="id" use="required"/>
            <xs:attribute type="xs:IDREF" name="project" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Project">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute type="xs:ID" name="id" use="required"/>
                    <xs:attribute type="xs:string" name="description" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="flagType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="active"/>
            <xs:enumeration value="deleted"/>
            <xs:enumeration value="superuser"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="groupType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="REGISTERING"/>
            <xs:enumeration value="CURRENT"/>
            <xs:enumeration value="FINISHED"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="emailAddress">
        <xs:restriction base="xs:string">
            <xs:pattern value="[^@]+@[^\.]+\..+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="City" type="cityType"/>

    <xs:complexType name="cityType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="id" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== blaec/masterjava_3_200617/src/test/resources/payload.xml
<Payload xmlns="http://javaops.ru"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://javaops.ru payload.xsd">
    <Users>
        <User flag="active" city="kiv" email="gmail@gmail.com">
            <fullName>Full Name</fullName>
        </User>
        <User flag="superuser" city="spb" email="admin@javaops.ru">
            <fullName>Admin</fullName>
        </User>
        <User flag="deleted" city="spb" email="mail@yandex.ru">
            <fullName>Deleted</fullName>
        </User>
    </Users>
    <Groups>
        <Group id="masterjava01" project="mj" type="CURRENT"/>
    </Groups>
    <Cities>
        <City id="spb">Санкт-Петербург</City>
        <City id="kiv">Киев</City>
        <City id="mnsk">Минск</City>
    </Cities>
    <Projects>
        <Project id="mj" description="masterjava description">masterjava</Project>
        <Project id="tj" description="topjava description">topjava</Project>
    </Projects>
</Payload>
